language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

cache:
  directories:
  - $HOME/.composer/cache
notifications:
  email: false
  slack:
    secure: R1mGJsr2JUJeUf+BAqNcZr7okImOq8VpKqyKDBAnuF4mZf1gIrcW48H6hqAIalzirqzCd16AKui9JVWtYQ8/NwDWczXVYeLoR26kSN9nGSTLhSf15ozXCAwLQLdW4YTogXGG2in98YKQxEYpUXiX1FEeP8POgsiTPAqn6Br4nvI=

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

